# Generated by Django 5.2.17 on 2026-08-16 08:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_seed_initial_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('postcode', models.CharField(blank=True, max_length=12)),
                ('party_date', models.DateField(blank=True, null=True)),
                ('party_date_unknown', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('normalised_email', models.CharField(blank=True, db_index=True, max_length=254)),
                ('normalised_phone', models.CharField(blank=True, db_index=True, max_length=40)),
                ('source', models.CharField(choices=[('online', 'Online'), ('store', 'Store')], max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('waiting_for_reply', 'Waiting for reply'), ('follow_up', 'Follow-up'), ('booked', 'Booked'), ('closed', 'Closed')], default='new', max_length=30)),
                ('booking_amount_aud', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('closed_reason', models.CharField(blank=True, choices=[('unable_to_contact', 'Unable to contact'), ('customer_no_longer_interested', 'Customer no longer interested'), ('price', 'Price'), ('other', 'Other')], max_length=40)),
                ('closed_reason_details', models.TextField(blank=True)),
                ('follow_up_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('zumo_conversation_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('original_zumo_message', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='accounts.location')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enquiries',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('author_display_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='enquiries.enquiry')),
            ],
            options={
                'db_table': 'notes',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ZumoImportDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zumo_conversation_id', models.CharField(max_length=255, unique=True)),
                ('zumo_conversation_url', models.URLField(max_length=1000)),
                ('decision', models.CharField(choices=[('imported', 'Imported'), ('ignored', 'Ignored')], max_length=10)),
                ('detected_postcode', models.CharField(blank=True, max_length=12)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('original_message_snapshot', models.TextField(blank=True)),
                ('detected_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zumo_decisions', to='accounts.location')),
                ('linked_enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zumo_decisions', to='enquiries.enquiry')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zumo_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zumo_import_decisions',
            },
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['location', 'source', 'status'], name='enquiries_locatio_ce2d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['follow_up_due_date'], name='enquiries_follow__d7fe9c_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['created_at'], name='enquiries_created_87e45c_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['updated_at'], name='enquiries_updated_c3a181_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['archived'], name='enquiries_archive_d77966_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['party_date'], name='enquiries_party_d_60b71a_idx'),
        ),
    ]
