# Generated by Django 5.2.17 on 2026-09-30 02:26

from django.db import migrations, models


def map_canberra_room_types(apps, schema_editor):
    PartySummary = apps.get_model('party_summaries', 'PartySummary')
    summaries = PartySummary.objects.filter(location__code='canberra')
    package_room_types = {
        'classic_weekday': 'single',
        'single_weekday': 'single',
        'single_weekend': 'single',
        'double_lite_weekday': 'double_lite',
        'double_lite_weekend': 'double_lite',
        'double_weekday': 'double',
        'double_weekend': 'double',
        'private_weekday_2hour': 'private_2hour',
        'private_weekend_2hour': 'private_2hour',
        'private_weekday_3hour': 'private_3hour',
        'private_weekend_3hour': 'private_3hour',
    }
    for package_name, room_type in package_room_types.items():
        summaries.filter(package_name=package_name).update(room_type=room_type)
    # Older/custom Canberra private bookings did not store their duration.
    # Keep them usable by choosing the shorter private package by default.
    summaries.filter(room_type='private').update(room_type='private_2hour')


def restore_legacy_room_types(apps, schema_editor):
    PartySummary = apps.get_model('party_summaries', 'PartySummary')
    summaries = PartySummary.objects.filter(location__code='canberra')
    summaries.filter(room_type='double_lite').update(room_type='double')
    summaries.filter(room_type__in=('private_2hour', 'private_3hour')).update(room_type='private')


class Migration(migrations.Migration):

    dependencies = [
        ('party_summaries', '0006_alter_partysummary_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partysummary',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double_lite', 'Double room Lite'), ('double', 'Double'), ('triple', 'Triple'), ('private', 'Private'), ('private_2hour', 'Private 2 hour'), ('private_3hour', 'Private 3 hour'), ('small_gathering', 'Small gathering')], max_length=30),
        ),
        migrations.RunPython(map_canberra_room_types, restore_legacy_room_types),
    ]
