# Generated by Django 5.2.17 on 2026-10-02 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_initial_accounts'),
        ('party_summaries', '0009_partybillitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partysummary',
            name='rsvp_information',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PartyIntakeLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_number', models.CharField(blank=True, max_length=50)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_party_intake_links', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_intake_links', to='accounts.location')),
                ('summary', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_link', to='party_summaries.partysummary')),
            ],
            options={
                'db_table': 'party_intake_links',
                'ordering': ('-created_at',),
            },
        ),
    ]
